# Generated by Django 4.2.6 on 2023-10-14 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipients', models.TextField()),
                ('message', models.TextField()),
                ('mode', models.CharField(default='sms', max_length=8)),
                ('group', models.CharField(default='all', max_length=50)),
                ('broadcast_dt', models.DateTimeField()),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
