# Generated by Django 4.2.6 on 2023-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('ministry', models.CharField(max_length=100, verbose_name='Ministry employed under e.g. Ministry of Education')),
                ('job_position', models.CharField(max_length=100, verbose_name='Job position e.g. Senior Teacher/Accountant')),
                ('salary_scale', models.CharField(max_length=2, verbose_name='Salary scale e.g. B2/C1')),
            ],
        ),
    ]
