# Generated by Django 4.2.6 on 2023-10-16 11:24

import broadcast.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcast', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_details',
            field=models.CharField(max_length=8, verbose_name='Contact number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(validators=[broadcast.models.valid_employee_dob]),
        ),
    ]
