# Generated by Django 4.2.6 on 2023-10-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_employee_contact_details_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
